name: Triggers
on:
  pull_request:
    types: [opened]
  issues:
    types: [edited]
  issue_comment:
    types: [edited]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
      - name: Run Hello World Script
        run: node index.js
